#!/usr/bin/env node

// QualGent Job CLI - Simple wrapper
const { spawn } = require('child_process');
const path = require('path');

// Get the directory where this script is located
const scriptDir = __dirname;
const cliPath = path.join(scriptDir, 'src', 'cli', 'index.js');

// Pass all arguments to the actual CLI
const child = spawn('node', [cliPath, ...process.argv.slice(2)], {
  stdio: 'inherit',
  cwd: scriptDir
});

child.on('exit', (code) => {
  process.exit(code || 0);
});
